/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnimeEntry = IDL.Record({
  'airedDate' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'airingStatus' : IDL.Text,
  'anilistId' : IDL.Nat,
  'episodesAvailable' : IDL.Nat,
  'genres' : IDL.Vec(IDL.Text),
  'publicRating' : IDL.Nat,
  'coverUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WatchlistEntry = IDL.Record({
  'personalRating' : IDL.Float64,
  'anime' : AnimeEntry,
  'notes' : IDL.Text,
  'alternateTitles' : IDL.Vec(IDL.Text),
  'isBookmarked' : IDL.Bool,
  'episodesWatched' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'emailPublic' : IDL.Bool,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'displaySettings' : IDL.Record({ 'boxSize' : IDL.Nat, 'rowSize' : IDL.Nat }),
});
export const Watchlist = IDL.Record({
  'entryCount' : IDL.Nat,
  'name' : IDL.Text,
  'entries' : IDL.Vec(WatchlistEntry),
  'isPublic' : IDL.Bool,
});
export const UserWatchlists = IDL.Record({ 'watchlists' : IDL.Vec(Watchlist) });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addAnimeToWatchlist' : IDL.Func(
      [IDL.Text, AnimeEntry, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkLoginLockout' : IDL.Func([], [IDL.Bool], ['query']),
  'clearMyExpiredLockout' : IDL.Func([], [], []),
  'copyAnimeToWatchlist' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'createWatchlist' : IDL.Func([IDL.Text], [], []),
  'deleteWatchlist' : IDL.Func([IDL.Text], [], []),
  'fetchAnimeFromAnilist' : IDL.Func([IDL.Text], [IDL.Text], []),
  'filterAnimeByGenres' : IDL.Func(
      [IDL.Vec(AnimeEntry), IDL.Vec(IDL.Text)],
      [IDL.Vec(AnimeEntry)],
      ['query'],
    ),
  'filterEntriesBySynopsis' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(WatchlistEntry)],
      ['query'],
    ),
  'getBookmarkedTitles' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(WatchlistEntry))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWatchlists' : IDL.Func([], [IDL.Opt(UserWatchlists)], ['query']),
  'getGlobalGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRemainingLockoutTime' : IDL.Func([], [IDL.Int], ['query']),
  'getSystemInfoContent' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWatchlists' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserWatchlists)],
      ['query'],
    ),
  'getWatchlistEntriesSortedByAiredDate' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Vec(WatchlistEntry)],
      ['query'],
    ),
  'getWatchlistEntriesSortedByPersonalRating' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Vec(WatchlistEntry)],
      ['query'],
    ),
  'getWatchlistEntriesSortedByTitle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WatchlistEntry)],
      ['query'],
    ),
  'getWatchlistNamesForAnime' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'moveAnimeToWatchlist' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'recordFailedLoginAttempt' : IDL.Func([], [], []),
  'removeAnimeFromWatchlist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'resetLoginAttempts' : IDL.Func([], [], []),
  'retrievePersistentState' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setWatchlistPublic' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'sortAnimeEntries' : IDL.Func(
      [IDL.Vec(AnimeEntry), IDL.Text, IDL.Bool],
      [IDL.Vec(AnimeEntry)],
      ['query'],
    ),
  'storePersistentState' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'toggleBookmark' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateGenres' : IDL.Func([IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  'updateTotalEpisodes' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateWatchlistEntry' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnimeEntry = IDL.Record({
    'airedDate' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'airingStatus' : IDL.Text,
    'anilistId' : IDL.Nat,
    'episodesAvailable' : IDL.Nat,
    'genres' : IDL.Vec(IDL.Text),
    'publicRating' : IDL.Nat,
    'coverUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WatchlistEntry = IDL.Record({
    'personalRating' : IDL.Float64,
    'anime' : AnimeEntry,
    'notes' : IDL.Text,
    'alternateTitles' : IDL.Vec(IDL.Text),
    'isBookmarked' : IDL.Bool,
    'episodesWatched' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'emailPublic' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'displaySettings' : IDL.Record({
      'boxSize' : IDL.Nat,
      'rowSize' : IDL.Nat,
    }),
  });
  const Watchlist = IDL.Record({
    'entryCount' : IDL.Nat,
    'name' : IDL.Text,
    'entries' : IDL.Vec(WatchlistEntry),
    'isPublic' : IDL.Bool,
  });
  const UserWatchlists = IDL.Record({ 'watchlists' : IDL.Vec(Watchlist) });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addAnimeToWatchlist' : IDL.Func(
        [IDL.Text, AnimeEntry, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkLoginLockout' : IDL.Func([], [IDL.Bool], ['query']),
    'clearMyExpiredLockout' : IDL.Func([], [], []),
    'copyAnimeToWatchlist' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'createWatchlist' : IDL.Func([IDL.Text], [], []),
    'deleteWatchlist' : IDL.Func([IDL.Text], [], []),
    'fetchAnimeFromAnilist' : IDL.Func([IDL.Text], [IDL.Text], []),
    'filterAnimeByGenres' : IDL.Func(
        [IDL.Vec(AnimeEntry), IDL.Vec(IDL.Text)],
        [IDL.Vec(AnimeEntry)],
        ['query'],
      ),
    'filterEntriesBySynopsis' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(WatchlistEntry)],
        ['query'],
      ),
    'getBookmarkedTitles' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(WatchlistEntry))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWatchlists' : IDL.Func([], [IDL.Opt(UserWatchlists)], ['query']),
    'getGlobalGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRemainingLockoutTime' : IDL.Func([], [IDL.Int], ['query']),
    'getSystemInfoContent' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWatchlists' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserWatchlists)],
        ['query'],
      ),
    'getWatchlistEntriesSortedByAiredDate' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Vec(WatchlistEntry)],
        ['query'],
      ),
    'getWatchlistEntriesSortedByPersonalRating' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Vec(WatchlistEntry)],
        ['query'],
      ),
    'getWatchlistEntriesSortedByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WatchlistEntry)],
        ['query'],
      ),
    'getWatchlistNamesForAnime' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'moveAnimeToWatchlist' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'recordFailedLoginAttempt' : IDL.Func([], [], []),
    'removeAnimeFromWatchlist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'resetLoginAttempts' : IDL.Func([], [], []),
    'retrievePersistentState' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setWatchlistPublic' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'sortAnimeEntries' : IDL.Func(
        [IDL.Vec(AnimeEntry), IDL.Text, IDL.Bool],
        [IDL.Vec(AnimeEntry)],
        ['query'],
      ),
    'storePersistentState' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'toggleBookmark' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateGenres' : IDL.Func([IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)], [], []),
    'updateTotalEpisodes' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateWatchlistEntry' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };