/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AnimeEntry {
    airedDate: string;
    title: string;
    description: string;
    airingStatus: string;
    anilistId: bigint;
    episodesAvailable: bigint;
    genres: Array<string>;
    publicRating: bigint;
    coverUrl: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface WatchlistEntry {
    personalRating: number;
    anime: AnimeEntry;
    notes: string;
    alternateTitles: Array<string>;
    isBookmarked: boolean;
    episodesWatched: bigint;
}
export interface Watchlist {
    entryCount: bigint;
    name: string;
    entries: Array<WatchlistEntry>;
    isPublic: boolean;
}
export interface UserWatchlists {
    watchlists: Array<Watchlist>;
}
export interface UserProfile {
    emailPublic: boolean;
    name: string;
    email: string;
    displaySettings: {
        boxSize: bigint;
        rowSize: bigint;
    };
}
export interface http_header {
    value: string;
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addAnimeToWatchlist(watchlistName: string, anime: AnimeEntry, alternateTitles: Array<string>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkLoginLockout(): Promise<boolean>;
    clearMyExpiredLockout(): Promise<void>;
    copyAnimeToWatchlist(fromWatchlist: string, toWatchlist: string, anilistId: bigint): Promise<void>;
    createWatchlist(name: string): Promise<void>;
    deleteWatchlist(watchlistName: string): Promise<void>;
    fetchAnimeFromAnilist(graphqlQuery: string): Promise<string>;
    filterAnimeByGenres(animeEntries: Array<AnimeEntry>, genres: Array<string>): Promise<Array<AnimeEntry>>;
    filterEntriesBySynopsis(watchlistName: string, searchText: string): Promise<Array<WatchlistEntry>>;
    getBookmarkedTitles(watchlistName: string): Promise<Array<WatchlistEntry> | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerWatchlists(): Promise<UserWatchlists | null>;
    getGlobalGenres(): Promise<Array<string>>;
    getRemainingLockoutTime(): Promise<bigint>;
    getSystemInfoContent(): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserWatchlists(user: Principal): Promise<UserWatchlists | null>;
    getWatchlistEntriesSortedByAiredDate(watchlistName: string, ascending: boolean): Promise<Array<WatchlistEntry>>;
    getWatchlistEntriesSortedByPersonalRating(watchlistName: string, ascending: boolean): Promise<Array<WatchlistEntry>>;
    getWatchlistEntriesSortedByTitle(watchlistName: string): Promise<Array<WatchlistEntry>>;
    getWatchlistNamesForAnime(anilistId: bigint): Promise<Array<string>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    moveAnimeToWatchlist(fromWatchlist: string, toWatchlist: string, anilistId: bigint): Promise<void>;
    recordFailedLoginAttempt(): Promise<void>;
    removeAnimeFromWatchlist(watchlistName: string, anilistId: bigint): Promise<void>;
    resetLoginAttempts(): Promise<void>;
    retrievePersistentState(): Promise<Uint8Array | null>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setWatchlistPublic(watchlistName: string, isPublic: boolean): Promise<void>;
    sortAnimeEntries(animeEntries: Array<AnimeEntry>, sortBy: string, ascending: boolean): Promise<Array<AnimeEntry>>;
    storePersistentState(state: Uint8Array): Promise<void>;
    toggleBookmark(arg0: string, anilistId: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateGenres(arg0: string, anilistId: bigint, newGenres: Array<string>): Promise<void>;
    updateTotalEpisodes(anilistId: bigint, newTotalEpisodes: bigint): Promise<void>;
    updateWatchlistEntry(arg0: string, anilistId: bigint, personalRating: number, episodesWatched: bigint, notes: string): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole, UserWatchlists as _UserWatchlists, WatchlistEntry as _WatchlistEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAnimeToWatchlist(arg0: string, arg1: AnimeEntry, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnimeToWatchlist(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnimeToWatchlist(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async checkLoginLockout(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkLoginLockout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkLoginLockout();
            return result;
        }
    }
    async clearMyExpiredLockout(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMyExpiredLockout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMyExpiredLockout();
            return result;
        }
    }
    async copyAnimeToWatchlist(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.copyAnimeToWatchlist(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.copyAnimeToWatchlist(arg0, arg1, arg2);
            return result;
        }
    }
    async createWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWatchlist(arg0);
            return result;
        }
    }
    async deleteWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWatchlist(arg0);
            return result;
        }
    }
    async fetchAnimeFromAnilist(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAnimeFromAnilist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAnimeFromAnilist(arg0);
            return result;
        }
    }
    async filterAnimeByGenres(arg0: Array<AnimeEntry>, arg1: Array<string>): Promise<Array<AnimeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterAnimeByGenres(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterAnimeByGenres(arg0, arg1);
            return result;
        }
    }
    async filterEntriesBySynopsis(arg0: string, arg1: string): Promise<Array<WatchlistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterEntriesBySynopsis(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterEntriesBySynopsis(arg0, arg1);
            return result;
        }
    }
    async getBookmarkedTitles(arg0: string): Promise<Array<WatchlistEntry> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookmarkedTitles(arg0);
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookmarkedTitles(arg0);
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerWatchlists(): Promise<UserWatchlists | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWatchlists();
                return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWatchlists();
            return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
        }
    }
    async getGlobalGenres(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalGenres();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalGenres();
            return result;
        }
    }
    async getRemainingLockoutTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemainingLockoutTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemainingLockoutTime();
            return result;
        }
    }
    async getSystemInfoContent(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemInfoContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemInfoContent();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserWatchlists(arg0: Principal): Promise<UserWatchlists | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWatchlists(arg0);
                return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWatchlists(arg0);
            return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWatchlistEntriesSortedByAiredDate(arg0: string, arg1: boolean): Promise<Array<WatchlistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlistEntriesSortedByAiredDate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlistEntriesSortedByAiredDate(arg0, arg1);
            return result;
        }
    }
    async getWatchlistEntriesSortedByPersonalRating(arg0: string, arg1: boolean): Promise<Array<WatchlistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlistEntriesSortedByPersonalRating(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlistEntriesSortedByPersonalRating(arg0, arg1);
            return result;
        }
    }
    async getWatchlistEntriesSortedByTitle(arg0: string): Promise<Array<WatchlistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlistEntriesSortedByTitle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlistEntriesSortedByTitle(arg0);
            return result;
        }
    }
    async getWatchlistNamesForAnime(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlistNamesForAnime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlistNamesForAnime(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async moveAnimeToWatchlist(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveAnimeToWatchlist(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveAnimeToWatchlist(arg0, arg1, arg2);
            return result;
        }
    }
    async recordFailedLoginAttempt(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordFailedLoginAttempt();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordFailedLoginAttempt();
            return result;
        }
    }
    async removeAnimeFromWatchlist(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAnimeFromWatchlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAnimeFromWatchlist(arg0, arg1);
            return result;
        }
    }
    async resetLoginAttempts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetLoginAttempts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetLoginAttempts();
            return result;
        }
    }
    async retrievePersistentState(): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.retrievePersistentState();
                return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retrievePersistentState();
            return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setWatchlistPublic(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWatchlistPublic(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWatchlistPublic(arg0, arg1);
            return result;
        }
    }
    async sortAnimeEntries(arg0: Array<AnimeEntry>, arg1: string, arg2: boolean): Promise<Array<AnimeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.sortAnimeEntries(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sortAnimeEntries(arg0, arg1, arg2);
            return result;
        }
    }
    async storePersistentState(arg0: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storePersistentState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storePersistentState(arg0);
            return result;
        }
    }
    async toggleBookmark(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleBookmark(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleBookmark(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateGenres(arg0: string, arg1: bigint, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGenres(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGenres(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTotalEpisodes(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTotalEpisodes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTotalEpisodes(arg0, arg1);
            return result;
        }
    }
    async updateWatchlistEntry(arg0: string, arg1: bigint, arg2: number, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWatchlistEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWatchlistEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_UserRole_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(uploadFile, downloadFile, value);
}
function from_candid_opt_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_WatchlistEntry>]): Array<WatchlistEntry> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserWatchlists]): UserWatchlists | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
