/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnimeEntry {
  'airedDate' : string,
  'title' : string,
  'description' : string,
  'airingStatus' : string,
  'anilistId' : bigint,
  'episodesAvailable' : bigint,
  'genres' : Array<string>,
  'publicRating' : bigint,
  'coverUrl' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'emailPublic' : boolean,
  'name' : string,
  'email' : string,
  'displaySettings' : { 'boxSize' : bigint, 'rowSize' : bigint },
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWatchlists { 'watchlists' : Array<Watchlist> }
export interface Watchlist {
  'entryCount' : bigint,
  'name' : string,
  'entries' : Array<WatchlistEntry>,
  'isPublic' : boolean,
}
export interface WatchlistEntry {
  'personalRating' : number,
  'anime' : AnimeEntry,
  'notes' : string,
  'alternateTitles' : Array<string>,
  'isBookmarked' : boolean,
  'episodesWatched' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addAnimeToWatchlist' : ActorMethod<
    [string, AnimeEntry, Array<string>],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkLoginLockout' : ActorMethod<[], boolean>,
  'clearMyExpiredLockout' : ActorMethod<[], undefined>,
  'copyAnimeToWatchlist' : ActorMethod<[string, string, bigint], undefined>,
  'createWatchlist' : ActorMethod<[string], undefined>,
  'deleteWatchlist' : ActorMethod<[string], undefined>,
  'fetchAnimeFromAnilist' : ActorMethod<[string], string>,
  'filterAnimeByGenres' : ActorMethod<
    [Array<AnimeEntry>, Array<string>],
    Array<AnimeEntry>
  >,
  'filterEntriesBySynopsis' : ActorMethod<
    [string, string],
    Array<WatchlistEntry>
  >,
  'getBookmarkedTitles' : ActorMethod<[string], [] | [Array<WatchlistEntry>]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWatchlists' : ActorMethod<[], [] | [UserWatchlists]>,
  'getGlobalGenres' : ActorMethod<[], Array<string>>,
  'getRemainingLockoutTime' : ActorMethod<[], bigint>,
  'getSystemInfoContent' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWatchlists' : ActorMethod<[Principal], [] | [UserWatchlists]>,
  'getWatchlistEntriesSortedByAiredDate' : ActorMethod<
    [string, boolean],
    Array<WatchlistEntry>
  >,
  'getWatchlistEntriesSortedByPersonalRating' : ActorMethod<
    [string, boolean],
    Array<WatchlistEntry>
  >,
  'getWatchlistEntriesSortedByTitle' : ActorMethod<
    [string],
    Array<WatchlistEntry>
  >,
  'getWatchlistNamesForAnime' : ActorMethod<[bigint], Array<string>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moveAnimeToWatchlist' : ActorMethod<[string, string, bigint], undefined>,
  'recordFailedLoginAttempt' : ActorMethod<[], undefined>,
  'removeAnimeFromWatchlist' : ActorMethod<[string, bigint], undefined>,
  'resetLoginAttempts' : ActorMethod<[], undefined>,
  'retrievePersistentState' : ActorMethod<[], [] | [Uint8Array]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setWatchlistPublic' : ActorMethod<[string, boolean], undefined>,
  'sortAnimeEntries' : ActorMethod<
    [Array<AnimeEntry>, string, boolean],
    Array<AnimeEntry>
  >,
  'storePersistentState' : ActorMethod<[Uint8Array], undefined>,
  'toggleBookmark' : ActorMethod<[string, bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateGenres' : ActorMethod<[string, bigint, Array<string>], undefined>,
  'updateTotalEpisodes' : ActorMethod<[bigint, bigint], undefined>,
  'updateWatchlistEntry' : ActorMethod<
    [string, bigint, number, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];